name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_KEY }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      ID_RSA: ${{ secrets.ID_RSA }}
      JENK_RSA: ${{ secrets.JENK_RSA }}
      working-directory: .
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Save Ubuntu Public key to file for terraform
        run: echo $ID_RSA > id_rsa.pub

      - name: Save Jenkins SSH Public key to file for terraform
        run: echo $JENK_RSA > jenk.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
