name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      YC_ACCESS_KEY: ${{ secrets.YC_ACCESS_KEY }}
      YC_SECRET_KEY: ${{ secrets.YC_SECRET_KEY }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      ID_RSA: ${{ secrets.ID_RSA }}
      working-directory: .
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Save SSH Public key to file for terraform
        run: echo $ID_RSA > ~/.ssh/id_rsa.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

